services:

  app:
    build: .
    ports:
      - "4000:3000"
    networks:
      - blogtree
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    
  postgres:
    image: postgres:15-alpine
    container_name: pga
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - blogtree
    

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - blogtree

volumes:
  redis_data:
  pg_data:

networks:
  blogtree:
    driver: bridge