services:

  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - blogtree
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.docker
    
  postgres:
    image: postgres:15-alpine
    container_name: pga
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env.docker
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - blogtree
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d local"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - blogtree
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
  pg_data:

networks:
  blogtree:
    driver: bridge